### ISSUE TITLE
(2) Feature: Visa vädervarning alert om dåligt väder upptäckt

### ISSUE THREAD

**Issue by gusbacke** [SlowDeepCoder/GreenCal#8]
(2) Som en användare vill jag se en varning om det är dåligt väder  så att jag kan minimera risker

**Comment by gusbacke** [comment]
WeatherAlert visas inte. 
Får konstiga fel i konsolen, svårt att fixa.

**Comment by OshedheMunasinghe** [comment]
> WeatherAlert visas inte.
> Får konstiga fel i konsolen, svårt att fixa.

Dear Customer,
Thank you for contacting us. We appreciate the opportunity to assist you.

In that case, we recommend that you clear data through:
Settings - App - three dots on the top right - show system maps- choose the app - storage - clear data.

Thank you for using our services. Your satisfaction is very important to us. 

Kind regard but we don't give a fuck,
Customers Serice Center GreenCal.


(Vi ska fixa efter presentationen! Jag ska fixa om data också som du har pekat test() där component!!) 
😇

**Comment by OshedheMunasinghe** [comment]
Nu hänger jag inte med.. 
Så jag behöver då inte lösa WeatherInfo.vue? @gusbacke :)

**Comment by OshedheMunasinghe** [comment]
Är den löst så behöver jag inte fortsätta WeatherInfo.vue.
